### ISSUE TITLE
Add support for RED Devices

### ISSUE THREAD

**Issue by pietro95** [matthias1232/kpc_sophosxg#1]
Hello,

Is possible to add to this plugin a check for RED devices connected to the firewall?

**Comment by matthias1232** [comment]
Hi @pietro95 

the MIB File from Sophos doesnt show me anything about the RED Tunnels. The only thing i can see are IPSec Tunnels, but i also did not add them because the SNMP Check shows only the Tunnel without any connection state, so it would not make sense to implement it.
If someone finds a way how to Monitor RED Tunnels and VPN Tunnels i would be up for implementing it but i cant find it in the SNMP MIB File.
![image](https://github.com/matthias1232/kpc_sophosxg/assets/5358267/deea3990-9c64-437e-95ec-1dc5d7e92706)

**Comment by matthias1232** [comment]
MIB File does not include Sophos REDs.
